import type { Metadata } from "next";
import { Poppins } from '@next/font/google';
import "./globals.css";

// Gunakan font Poppins untuk seluruh halaman dengan bobot 400, 700, dan 900
const poppins = Poppins({
  weight: ['400', '700', '900'], // Tambahkan bobot yang diinginkan
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-gray-100 antialiased">
        {/* Header atau Navbar */}
        <header className="bg-white shadow-md">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span className="ml-3 text-xl">Tailblocks</span>
    </a>
    <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center font-bold ">
      <a className="mr-5 hover:text-blue-600 text-black">First Link</a>
      <a className="mr-5 hover:text-blue-600 text-black">Second Link</a>
      <a className="mr-5 hover:text-blue-600 text-black">Third Link</a>
      <a className="mr-5 hover:text-blue-600 text-black">Fourth Link</a>
    </nav>
    
  </div>
        </header>

        {/* Konten Halaman */}
        {children}
      </body>
    </html>
  );
}
